### PR TITLE
fixed: color images

### LINKED ISSUE #104: Multiframe modality for color images
Debug photometric interpretation in wado image loader.

### PR DESCRIPTION
**Pull request by daron1337**
fix #104

### CODE REVIEW

File: imaging/loaders/multiframeLoader.js [hunk 1]
```diff
@@ -268,7 +270,7 @@ let createCustomImage = function (id, imageId, frameIndex, metadata) {
           return canvas;
         };
       } else {
-        image.render = cornerstone.renderGrayscaleImage;
+        image.render = undefined;
       }
```
Comment (ronzim) [inline imaging/loaders/multiframeLoader.js:275]: TODO move image.render outside if / else

**Review by ronzim — APPROVED** [review]
